name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: embed
        path: embed
        if-no-files-found: warn
        retention-days: 90
        compression-level: 6
        overwrite: false
        include-hidden-files: false


